import type { ThemeColors, TokenColor } from '@/types'
import { DEFAULT_DARK_COLORS, DEFAULT_TOKEN_COLORS } from './default-theme'

export interface ThemeTemplate {
  id: string
  name: string
  type: 'dark' | 'light'
  description: string
  colors: ThemeColors
  tokenColors: TokenColor[]
}

const LIGHT_BASE_TOKENS: TokenColor[] = [
  { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#008000', fontStyle: 'italic' } },
  { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#a31515' } },
  { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#098658' } },
  { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#0000ff' } },
  { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#0000ff' } },
  { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#000000' } },
  { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#795e26' } },
  { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#267f99' } },
  { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#001080' } },
  { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#001080' } },
  { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#001080' } },
  { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#800000' } },
  { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#e50000' } },
  { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#811f3f' } },
  { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#ee0000' } },
]

export const THEME_TEMPLATES: ThemeTemplate[] = [
  // ===== Classic Dark =====
  {
    id: 'classic-dark',
    name: 'Classic Dark',
    type: 'dark',
    description: 'シンプルで使いやすい定番ダークテーマ',
    colors: { ...DEFAULT_DARK_COLORS },
    tokenColors: [...DEFAULT_TOKEN_COLORS],
  },

  // ===== Classic Light =====
  {
    id: 'classic-light',
    name: 'Classic Light',
    type: 'light',
    description: 'シンプルで使いやすい定番ライトテーマ',
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'editor.lineHighlightBackground': '#f0f0f0',
      'editor.selectionBackground': '#add6ff',
      'editor.selectionHighlightBackground': '#add6ff80',
      'editor.wordHighlightBackground': '#57575740',
      'editor.findMatchBackground': '#a8ac94',
      'editor.findMatchHighlightBackground': '#ea5c0040',
      'editorGutter.background': '#ffffff',
      'editorLineNumber.foreground': '#237893',
      'editorLineNumber.activeForeground': '#0b216f',
      'sideBar.background': '#f3f3f3',
      'sideBar.foreground': '#616161',
      'sideBar.border': '#e5e5e5',
      'sideBarTitle.foreground': '#6f6f6f',
      'sideBarSectionHeader.background': '#e0e0e0',
      'sideBarSectionHeader.foreground': '#6f6f6f',
      'activityBar.background': '#2c2c2c',
      'activityBar.foreground': '#ffffff',
      'activityBar.inactiveForeground': '#ffffff66',
      'activityBarBadge.background': '#007acc',
      'activityBarBadge.foreground': '#ffffff',
      'tab.activeBackground': '#ffffff',
      'tab.activeForeground': '#333333',
      'tab.inactiveBackground': '#ececec',
      'tab.inactiveForeground': '#33333380',
      'tab.border': '#f3f3f3',
      'tab.activeBorder': '#f3f3f3',
      'titleBar.activeBackground': '#dddddd',
      'titleBar.activeForeground': '#333333',
      'titleBar.inactiveBackground': '#dddddd99',
      'titleBar.inactiveForeground': '#33333399',
      'statusBar.background': '#007acc',
      'statusBar.foreground': '#ffffff',
      'statusBar.border': '#e5e5e5',
      'statusBar.debuggingBackground': '#cc6633',
      'statusBar.noFolderBackground': '#68217a',
      'panel.background': '#ffffff',
      'panel.border': '#e5e5e5',
      'panelTitle.activeBorder': '#424242',
      'panelTitle.activeForeground': '#424242',
      'panelTitle.inactiveForeground': '#42424280',
      'input.background': '#ffffff',
      'input.foreground': '#616161',
      'input.border': '#cecece',
      'input.placeholderForeground': '#767676',
      'inputOption.activeBorder': '#007acc',
      'dropdown.background': '#ffffff',
      'dropdown.foreground': '#616161',
      'dropdown.border': '#cecece',
      'button.background': '#007acc',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#0062a3',
      'list.activeSelectionBackground': '#0060c0',
      'list.activeSelectionForeground': '#ffffff',
      'list.hoverBackground': '#e8e8e8',
      'list.hoverForeground': '#2e2e2e',
      'list.inactiveSelectionBackground': '#e4e6f1',
      'list.highlightForeground': '#0066bf',
      'scrollbar.shadow': '#dddddd',
      'scrollbarSlider.background': '#64646466',
      'scrollbarSlider.hoverBackground': '#646464b3',
      'scrollbarSlider.activeBackground': '#00000099',
      'minimap.background': '#ffffff',
      'minimap.selectionHighlight': '#add6ff',
      'breadcrumb.foreground': '#616161',
      'breadcrumb.focusForeground': '#2e2e2e',
      'breadcrumb.activeSelectionForeground': '#2e2e2e',
      focusBorder: '#0090f1',
      foreground: '#616161',
      'widget.shadow': '#a8a8a829',
      'selection.background': '#add6ff',
      errorForeground: '#a1260d',
    },
    tokenColors: LIGHT_BASE_TOKENS,
  },

  // ===== Vivid Jungle =====
  {
    id: 'vivid-jungle',
    name: 'Vivid Jungle',
    type: 'dark',
    description: '鮮やかなグリーンとピンクが映えるダークテーマ',
    colors: {
      'editor.background': '#1e2a1f',
      'editor.foreground': '#f5f5ea',
      'editor.lineHighlightBackground': '#2d3b2e',
      'editor.selectionBackground': '#3a4a3a',
      'editor.selectionHighlightBackground': '#3a4a3a80',
      'editor.wordHighlightBackground': '#3a4a3a',
      'editor.findMatchBackground': '#f0e68c60',
      'editor.findMatchHighlightBackground': '#f0e68c40',
      'editorGutter.background': '#1e2a1f',
      'editorLineNumber.foreground': '#8a8a85',
      'editorLineNumber.activeForeground': '#bdbdb8',
      'sideBar.background': '#1a1f24',
      'sideBar.foreground': '#f5f5ea',
      'sideBar.border': '#14181c',
      'sideBarTitle.foreground': '#f5f5ea',
      'sideBarSectionHeader.background': '#1a1f24',
      'sideBarSectionHeader.foreground': '#f5f5ea',
      'activityBar.background': '#1e2a1f',
      'activityBar.foreground': '#f5f5ea',
      'activityBar.inactiveForeground': '#f5f5ea66',
      'activityBarBadge.background': '#8bc34a',
      'activityBarBadge.foreground': '#1e2a1f',
      'tab.activeBackground': '#1e2a1f',
      'tab.activeForeground': '#f5f5ea',
      'tab.inactiveBackground': '#1a1f24',
      'tab.inactiveForeground': '#f5f5ea80',
      'tab.border': '#14181c',
      'tab.activeBorder': '#8bc34a',
      'titleBar.activeBackground': '#161b1f',
      'titleBar.activeForeground': '#f5f5ea',
      'titleBar.inactiveBackground': '#161b1f99',
      'titleBar.inactiveForeground': '#f5f5ea99',
      'statusBar.background': '#8bc34a',
      'statusBar.foreground': '#1e2a1f',
      'statusBar.border': '#14181c',
      'statusBar.debuggingBackground': '#ff9800',
      'statusBar.noFolderBackground': '#9c27b0',
      'panel.background': '#1e2a1f',
      'panel.border': '#3a4a3a',
      'panelTitle.activeBorder': '#f5f5ea',
      'panelTitle.activeForeground': '#f5f5ea',
      'panelTitle.inactiveForeground': '#f5f5ea80',
      'input.background': '#2d3b2e',
      'input.foreground': '#f5f5ea',
      'input.border': '#3a4a3a',
      'input.placeholderForeground': '#f5f5ea80',
      'inputOption.activeBorder': '#8bc34a',
      'dropdown.background': '#2d3b2e',
      'dropdown.foreground': '#f5f5ea',
      'dropdown.border': '#3a4a3a',
      'button.background': '#8bc34a',
      'button.foreground': '#1e2a1f',
      'button.hoverBackground': '#9ccc65',
      'list.activeSelectionBackground': '#3a4a3a',
      'list.activeSelectionForeground': '#f5f5ea',
      'list.hoverBackground': '#2d3b2e',
      'list.hoverForeground': '#f5f5ea',
      'list.inactiveSelectionBackground': '#2d3b2e',
      'list.highlightForeground': '#8bc34a',
      'scrollbar.shadow': '#00000050',
      'scrollbarSlider.background': '#3a4a3a80',
      'scrollbarSlider.hoverBackground': '#3a4a3ab3',
      'scrollbarSlider.activeBackground': '#3a4a3aff',
      'minimap.background': '#1e2a1f',
      'minimap.selectionHighlight': '#3a4a3a',
      'breadcrumb.foreground': '#f5f5eacc',
      'breadcrumb.focusForeground': '#f5f5ea',
      'breadcrumb.activeSelectionForeground': '#f5f5ea',
      focusBorder: '#8bc34a',
      foreground: '#f5f5ea',
      'widget.shadow': '#00000050',
      'selection.background': '#3a4a3a',
      errorForeground: '#e91e63',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#6a6a65', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#ffeb3b' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#9c27b0' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#9c27b0' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#e91e63' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#e91e63' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#8bc34a' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#8bc34a', fontStyle: 'underline' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#f5f5ea' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#ff9800', fontStyle: 'italic' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#f5f5ea' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#e91e63' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#8bc34a' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#ffeb3b' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#9c27b0' } },
    ],
  },

  // ===== Twilight Purple =====
  {
    id: 'twilight-purple',
    name: 'Twilight Purple',
    type: 'dark',
    description: '紫を基調としたモダンなダークテーマ',
    colors: {
      'editor.background': '#2a1f3a',
      'editor.foreground': '#f5f0ff',
      'editor.lineHighlightBackground': '#3d2f4d75',
      'editor.selectionBackground': '#3d2f4d',
      'editor.selectionHighlightBackground': '#3d2f4d75',
      'editor.wordHighlightBackground': '#b39ddb50',
      'editor.findMatchBackground': '#ffab9180',
      'editor.findMatchHighlightBackground': '#ffab9140',
      'editorGutter.background': '#2a1f3a',
      'editorLineNumber.foreground': '#7e57c2',
      'editorLineNumber.activeForeground': '#f5f0ff',
      'sideBar.background': '#1f1628',
      'sideBar.foreground': '#f5f0ff',
      'sideBar.border': '#16101f',
      'sideBarTitle.foreground': '#f5f0ff',
      'sideBarSectionHeader.background': '#1f1628',
      'sideBarSectionHeader.foreground': '#f5f0ff',
      'activityBar.background': '#3d2f4d',
      'activityBar.foreground': '#f5f0ff',
      'activityBar.inactiveForeground': '#7e57c2',
      'activityBarBadge.background': '#e91e63',
      'activityBarBadge.foreground': '#f5f0ff',
      'tab.activeBackground': '#2a1f3a',
      'tab.activeForeground': '#f5f0ff',
      'tab.inactiveBackground': '#1f1628',
      'tab.inactiveForeground': '#7e57c2',
      'tab.border': '#16101f',
      'tab.activeBorder': '#e91e63',
      'titleBar.activeBackground': '#1f1628',
      'titleBar.activeForeground': '#f5f0ff',
      'titleBar.inactiveBackground': '#1f162899',
      'titleBar.inactiveForeground': '#7e57c2',
      'statusBar.background': '#16101f',
      'statusBar.foreground': '#f5f0ff',
      'statusBar.border': '#16101f',
      'statusBar.debuggingBackground': '#f44336',
      'statusBar.noFolderBackground': '#16101f',
      'panel.background': '#2a1f3a',
      'panel.border': '#9575cd',
      'panelTitle.activeBorder': '#e91e63',
      'panelTitle.activeForeground': '#f5f0ff',
      'panelTitle.inactiveForeground': '#7e57c2',
      'input.background': '#2a1f3a',
      'input.foreground': '#f5f0ff',
      'input.border': '#16101f',
      'input.placeholderForeground': '#7e57c2',
      'inputOption.activeBorder': '#9575cd',
      'dropdown.background': '#3d2f4d',
      'dropdown.foreground': '#f5f0ff',
      'dropdown.border': '#16101f',
      'button.background': '#3d2f4d',
      'button.foreground': '#f5f0ff',
      'button.hoverBackground': '#7e57c2',
      'list.activeSelectionBackground': '#3d2f4d',
      'list.activeSelectionForeground': '#f5f0ff',
      'list.hoverBackground': '#3d2f4d75',
      'list.hoverForeground': '#f5f0ff',
      'list.inactiveSelectionBackground': '#3d2f4d75',
      'list.highlightForeground': '#b39ddb',
      'scrollbar.shadow': '#16101f',
      'scrollbarSlider.background': '#3d2f4d80',
      'scrollbarSlider.hoverBackground': '#3d2f4db3',
      'scrollbarSlider.activeBackground': '#7e57c2',
      'minimap.background': '#2a1f3a',
      'minimap.selectionHighlight': '#3d2f4d',
      'breadcrumb.foreground': '#7e57c2',
      'breadcrumb.focusForeground': '#f5f0ff',
      'breadcrumb.activeSelectionForeground': '#f5f0ff',
      focusBorder: '#7e57c2',
      foreground: '#f5f0ff',
      'widget.shadow': '#16101f80',
      'selection.background': '#3d2f4d',
      errorForeground: '#f44336',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#7e57c2', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#fff59d' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#9575cd' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#9575cd' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#e91e63' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#e91e63' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#66bb6a' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#b39ddb', fontStyle: 'italic' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#f5f0ff' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#ffab91', fontStyle: 'italic' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#4fc3f7' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#e91e63' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#66bb6a' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#f44336' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#e91e63' } },
    ],
  },

  // ===== Frost Blue =====
  {
    id: 'frost-blue',
    name: 'Frost Blue',
    type: 'dark',
    description: '落ち着いた寒色系の静かなダークテーマ',
    colors: {
      'editor.background': '#1f2937',
      'editor.foreground': '#e2e8f0',
      'editor.lineHighlightBackground': '#374151',
      'editor.selectionBackground': '#4b5563',
      'editor.selectionHighlightBackground': '#4b556380',
      'editor.wordHighlightBackground': '#4b5563',
      'editor.findMatchBackground': '#60a5fa66',
      'editor.findMatchHighlightBackground': '#60a5fa33',
      'editorGutter.background': '#1f2937',
      'editorLineNumber.foreground': '#6b7280',
      'editorLineNumber.activeForeground': '#e2e8f0',
      'sideBar.background': '#1f2937',
      'sideBar.foreground': '#e2e8f0',
      'sideBar.border': '#374151',
      'sideBarTitle.foreground': '#e2e8f0',
      'sideBarSectionHeader.background': '#374151',
      'sideBarSectionHeader.foreground': '#e2e8f0',
      'activityBar.background': '#1f2937',
      'activityBar.foreground': '#e2e8f0',
      'activityBar.inactiveForeground': '#6b7280',
      'activityBarBadge.background': '#3b82f6',
      'activityBarBadge.foreground': '#1f2937',
      'tab.activeBackground': '#374151',
      'tab.activeForeground': '#e2e8f0',
      'tab.inactiveBackground': '#1f2937',
      'tab.inactiveForeground': '#6b7280',
      'tab.border': '#374151',
      'tab.activeBorder': '#3b82f6',
      'titleBar.activeBackground': '#1f2937',
      'titleBar.activeForeground': '#e2e8f0',
      'titleBar.inactiveBackground': '#1f293799',
      'titleBar.inactiveForeground': '#e2e8f099',
      'statusBar.background': '#3b82f6',
      'statusBar.foreground': '#e2e8f0',
      'statusBar.border': '#374151',
      'statusBar.debuggingBackground': '#f59e0b',
      'statusBar.noFolderBackground': '#8b5cf6',
      'panel.background': '#1f2937',
      'panel.border': '#374151',
      'panelTitle.activeBorder': '#3b82f6',
      'panelTitle.activeForeground': '#e2e8f0',
      'panelTitle.inactiveForeground': '#6b7280',
      'input.background': '#374151',
      'input.foreground': '#e2e8f0',
      'input.border': '#6b7280',
      'input.placeholderForeground': '#6b7280',
      'inputOption.activeBorder': '#3b82f6',
      'dropdown.background': '#374151',
      'dropdown.foreground': '#e2e8f0',
      'dropdown.border': '#6b7280',
      'button.background': '#3b82f6',
      'button.foreground': '#e2e8f0',
      'button.hoverBackground': '#60a5fa',
      'list.activeSelectionBackground': '#4b5563',
      'list.activeSelectionForeground': '#e2e8f0',
      'list.hoverBackground': '#374151',
      'list.hoverForeground': '#e2e8f0',
      'list.inactiveSelectionBackground': '#374151',
      'list.highlightForeground': '#3b82f6',
      'scrollbar.shadow': '#1f293750',
      'scrollbarSlider.background': '#6b728080',
      'scrollbarSlider.hoverBackground': '#6b7280b3',
      'scrollbarSlider.activeBackground': '#6b7280ff',
      'minimap.background': '#1f2937',
      'minimap.selectionHighlight': '#4b5563',
      'breadcrumb.foreground': '#e2e8f0cc',
      'breadcrumb.focusForeground': '#e2e8f0',
      'breadcrumb.activeSelectionForeground': '#e2e8f0',
      focusBorder: '#3b82f6',
      foreground: '#e2e8f0',
      'widget.shadow': '#1f293760',
      'selection.background': '#4b5563',
      errorForeground: '#ef4444',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#6b7280', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#84cc16' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#8b5cf6' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#60a5fa' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#60a5fa' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#60a5fa' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#3b82f6' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#06b6d4' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#e2e8f0' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#e2e8f0' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#3b82f6' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#60a5fa' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#06b6d4' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#f59e0b' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#f59e0b' } },
    ],
  },

  // ===== Warm Teal Dark =====
  {
    id: 'warm-teal-dark',
    name: 'Warm Teal Dark',
    type: 'dark',
    description: 'ティールと暖色が調和した目に優しいダークテーマ',
    colors: {
      'editor.background': '#0f3443',
      'editor.foreground': '#a8dadc',
      'editor.lineHighlightBackground': '#1e5166',
      'editor.selectionBackground': '#2d6a7c',
      'editor.selectionHighlightBackground': '#2d6a7c80',
      'editor.wordHighlightBackground': '#1e5166',
      'editor.findMatchBackground': '#f77f0060',
      'editor.findMatchHighlightBackground': '#f77f0030',
      'editorGutter.background': '#0f3443',
      'editorLineNumber.foreground': '#6b7b7c',
      'editorLineNumber.activeForeground': '#d1d1d1',
      'sideBar.background': '#0a2e36',
      'sideBar.foreground': '#a8dadc',
      'sideBar.border': '#1e5166',
      'sideBarTitle.foreground': '#d1d1d1',
      'sideBarSectionHeader.background': '#1e5166',
      'sideBarSectionHeader.foreground': '#d1d1d1',
      'activityBar.background': '#0f3443',
      'activityBar.foreground': '#a8dadc',
      'activityBar.inactiveForeground': '#6b7b7c',
      'activityBarBadge.background': '#06ffa5',
      'activityBarBadge.foreground': '#0f3443',
      'tab.activeBackground': '#0f3443',
      'tab.activeForeground': '#f1faee',
      'tab.inactiveBackground': '#0a2e36',
      'tab.inactiveForeground': '#6b7b7c',
      'tab.border': '#1e5166',
      'tab.activeBorder': '#06ffa5',
      'titleBar.activeBackground': '#0a2e36',
      'titleBar.activeForeground': '#a8dadc',
      'titleBar.inactiveBackground': '#0a2e3699',
      'titleBar.inactiveForeground': '#a8dadc99',
      'statusBar.background': '#1e5166',
      'statusBar.foreground': '#a8dadc',
      'statusBar.border': '#1e5166',
      'statusBar.debuggingBackground': '#e63946',
      'statusBar.noFolderBackground': '#7209b7',
      'panel.background': '#0f3443',
      'panel.border': '#1e5166',
      'panelTitle.activeBorder': '#06ffa5',
      'panelTitle.activeForeground': '#d1d1d1',
      'panelTitle.inactiveForeground': '#6b7b7c',
      'input.background': '#1e5166',
      'input.foreground': '#a8dadc',
      'input.border': '#6b7b7c',
      'input.placeholderForeground': '#6b7b7c',
      'inputOption.activeBorder': '#06ffa5',
      'dropdown.background': '#1e5166',
      'dropdown.foreground': '#a8dadc',
      'dropdown.border': '#6b7b7c',
      'button.background': '#06ffa5',
      'button.foreground': '#0f3443',
      'button.hoverBackground': '#00d9a3',
      'list.activeSelectionBackground': '#1e5166',
      'list.activeSelectionForeground': '#f1faee',
      'list.hoverBackground': '#1e5166cc',
      'list.hoverForeground': '#a8dadc',
      'list.inactiveSelectionBackground': '#1e5166',
      'list.highlightForeground': '#06ffa5',
      'scrollbar.shadow': '#0f344350',
      'scrollbarSlider.background': '#6b7b7c80',
      'scrollbarSlider.hoverBackground': '#6b7b7cb3',
      'scrollbarSlider.activeBackground': '#6b7b7cff',
      'minimap.background': '#0f3443',
      'minimap.selectionHighlight': '#2d6a7c',
      'breadcrumb.foreground': '#a8dadc',
      'breadcrumb.focusForeground': '#d1d1d1',
      'breadcrumb.activeSelectionForeground': '#f1faee',
      focusBorder: '#06ffa5',
      foreground: '#a8dadc',
      'widget.shadow': '#0f344380',
      'selection.background': '#2d6a7c',
      errorForeground: '#e63946',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#6b7b7c', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#00d9a3' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#7209b7' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#f77f00' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#a8dadc' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#a8dadc' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#06ffa5' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#f77f00' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#a8dadc' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#a8dadc' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#06ffa5' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#06ffa5' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#d1d1d1' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#e63946' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#f77f00' } },
    ],
  },

  // ===== Midnight Ink =====
  {
    id: 'midnight-ink',
    name: 'Midnight Ink',
    type: 'dark',
    description: '深い漆黒にクリアな色彩が映えるモダンテーマ',
    colors: {
      'editor.background': '#0a0e1a',
      'editor.foreground': '#d1d5db',
      'editor.lineHighlightBackground': '#141824',
      'editor.selectionBackground': '#1e293b',
      'editor.selectionHighlightBackground': '#1e293b40',
      'editor.wordHighlightBackground': '#1e293b',
      'editor.findMatchBackground': '#f59e0baa',
      'editor.findMatchHighlightBackground': '#fbbf2450',
      'editorGutter.background': '#0a0e1a',
      'editorLineNumber.foreground': '#4b5563',
      'editorLineNumber.activeForeground': '#d1d5db',
      'sideBar.background': '#050711',
      'sideBar.foreground': '#d1d5db',
      'sideBar.border': '#1f293b',
      'sideBarTitle.foreground': '#d1d5db',
      'sideBarSectionHeader.background': '#050711',
      'sideBarSectionHeader.foreground': '#d1d5db',
      'activityBar.background': '#0a0e1a',
      'activityBar.foreground': '#d1d5db',
      'activityBar.inactiveForeground': '#4b5563',
      'activityBarBadge.background': '#3b82f6',
      'activityBarBadge.foreground': '#ffffff',
      'tab.activeBackground': '#0a0e1a',
      'tab.activeForeground': '#d1d5db',
      'tab.inactiveBackground': '#050711',
      'tab.inactiveForeground': '#6b7280',
      'tab.border': '#1f293b',
      'tab.activeBorder': '#f87171',
      'titleBar.activeBackground': '#050711',
      'titleBar.activeForeground': '#d1d5db',
      'titleBar.inactiveBackground': '#05071199',
      'titleBar.inactiveForeground': '#6b7280',
      'statusBar.background': '#0a0e1a',
      'statusBar.foreground': '#6b7280',
      'statusBar.border': '#1f293b',
      'statusBar.debuggingBackground': '#ef4444',
      'statusBar.noFolderBackground': '#0a0e1a',
      'panel.background': '#0a0e1a',
      'panel.border': '#1f293b',
      'panelTitle.activeBorder': '#f87171',
      'panelTitle.activeForeground': '#d1d5db',
      'panelTitle.inactiveForeground': '#6b7280',
      'input.background': '#0a0e1a',
      'input.foreground': '#d1d5db',
      'input.border': '#1f293b',
      'input.placeholderForeground': '#4b5563',
      'inputOption.activeBorder': '#3b82f6',
      'dropdown.background': '#141824',
      'dropdown.foreground': '#d1d5db',
      'dropdown.border': '#1f293b',
      'button.background': '#10b981',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#34d399',
      'list.activeSelectionBackground': '#1e293b80',
      'list.activeSelectionForeground': '#d1d5db',
      'list.hoverBackground': '#141824',
      'list.hoverForeground': '#d1d5db',
      'list.inactiveSelectionBackground': '#141824',
      'list.highlightForeground': '#60a5fa',
      'scrollbar.shadow': '#05071180',
      'scrollbarSlider.background': '#4b556380',
      'scrollbarSlider.hoverBackground': '#4b5563b3',
      'scrollbarSlider.activeBackground': '#4b5563ff',
      'minimap.background': '#0a0e1a',
      'minimap.selectionHighlight': '#1e293b',
      'breadcrumb.foreground': '#6b7280',
      'breadcrumb.focusForeground': '#d1d5db',
      'breadcrumb.activeSelectionForeground': '#d1d5db',
      focusBorder: '#3b82f6',
      foreground: '#d1d5db',
      'widget.shadow': '#05071180',
      'selection.background': '#1e293b',
      errorForeground: '#f87171',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#6b7280', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#93c5fd' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#60a5fa' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#60a5fa' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#f87171' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#f87171' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#a78bfa' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#fbbf24' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#fbbf24' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#d1d5db' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#60a5fa' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#86efac' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#60a5fa' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#93c5fd' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#60a5fa' } },
    ],
  },

  // ===== Dusk Harmony =====
  {
    id: 'dusk-harmony',
    name: 'Dusk Harmony',
    type: 'dark',
    description: '調和のとれた配色で長時間でも疲れにくいダークテーマ',
    colors: {
      'editor.background': '#2d3142',
      'editor.foreground': '#bfc0c0',
      'editor.lineHighlightBackground': '#31363f',
      'editor.selectionBackground': '#414552',
      'editor.selectionHighlightBackground': '#41455280',
      'editor.wordHighlightBackground': '#414552',
      'editor.findMatchBackground': '#e5a50d80',
      'editor.findMatchHighlightBackground': '#e5a50d40',
      'editorGutter.background': '#2d3142',
      'editorLineNumber.foreground': '#51576d',
      'editorLineNumber.activeForeground': '#bfc0c0',
      'sideBar.background': '#22262e',
      'sideBar.foreground': '#bfc0c0',
      'sideBar.border': '#181a1f',
      'sideBarTitle.foreground': '#bfc0c0',
      'sideBarSectionHeader.background': '#22262e',
      'sideBarSectionHeader.foreground': '#bfc0c0',
      'activityBar.background': '#2d3142',
      'activityBar.foreground': '#bfc0c0',
      'activityBar.inactiveForeground': '#51576d',
      'activityBarBadge.background': '#7287fd',
      'activityBarBadge.foreground': '#ffffff',
      'tab.activeBackground': '#2d3142',
      'tab.activeForeground': '#d9d9d9',
      'tab.inactiveBackground': '#22262e',
      'tab.inactiveForeground': '#63676d',
      'tab.border': '#181a1f',
      'tab.activeBorder': '#7287fd',
      'titleBar.activeBackground': '#2d3142',
      'titleBar.activeForeground': '#9ca3af',
      'titleBar.inactiveBackground': '#2d314299',
      'titleBar.inactiveForeground': '#9ca3af99',
      'statusBar.background': '#22262e',
      'statusBar.foreground': '#9ca3af',
      'statusBar.border': '#181a1f',
      'statusBar.debuggingBackground': '#f38ba8',
      'statusBar.noFolderBackground': '#22262e',
      'panel.background': '#2d3142',
      'panel.border': '#414552',
      'panelTitle.activeBorder': '#7287fd',
      'panelTitle.activeForeground': '#bfc0c0',
      'panelTitle.inactiveForeground': '#63676d',
      'input.background': '#1e1e2e',
      'input.foreground': '#bfc0c0',
      'input.border': '#414552',
      'input.placeholderForeground': '#63676d',
      'inputOption.activeBorder': '#7287fd',
      'dropdown.background': '#1e1e2e',
      'dropdown.foreground': '#bfc0c0',
      'dropdown.border': '#414552',
      'button.background': '#5875c3',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#6b83bd',
      'list.activeSelectionBackground': '#31363f',
      'list.activeSelectionForeground': '#d9d9d9',
      'list.hoverBackground': '#31363f',
      'list.hoverForeground': '#bfc0c0',
      'list.inactiveSelectionBackground': '#31363f',
      'list.highlightForeground': '#7287fd',
      'scrollbar.shadow': '#22262e80',
      'scrollbarSlider.background': '#51576d80',
      'scrollbarSlider.hoverBackground': '#5a637580',
      'scrollbarSlider.activeBackground': '#747d9180',
      'minimap.background': '#2d3142',
      'minimap.selectionHighlight': '#414552',
      'breadcrumb.foreground': '#63676d',
      'breadcrumb.focusForeground': '#bfc0c0',
      'breadcrumb.activeSelectionForeground': '#bfc0c0',
      focusBorder: '#7287fd',
      foreground: '#bfc0c0',
      'widget.shadow': '#22262e80',
      'selection.background': '#414552',
      errorForeground: '#f38ba8',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#63676d', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#a6e3a1' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#fab387' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#fab387' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#cba6f7' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#cba6f7' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#89b4fa' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#f9e2af' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#f38ba8' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#f38ba8' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#f38ba8' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#f38ba8' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#fab387' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#fab387' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#fab387' } },
    ],
  },

  // ===== Warm Teal Light =====
  {
    id: 'warm-teal-light',
    name: 'Warm Teal Light',
    type: 'light',
    description: 'ティールと暖色が調和した目に優しいライトテーマ',
    colors: {
      'editor.background': '#fdf6e3',
      'editor.foreground': '#657b83',
      'editor.lineHighlightBackground': '#eee8d5',
      'editor.selectionBackground': '#eee8d5',
      'editor.selectionHighlightBackground': '#eee8d580',
      'editor.wordHighlightBackground': '#eee8d5',
      'editor.findMatchBackground': '#b5890060',
      'editor.findMatchHighlightBackground': '#b5890030',
      'editorGutter.background': '#fdf6e3',
      'editorLineNumber.foreground': '#93a1a1',
      'editorLineNumber.activeForeground': '#586e75',
      'sideBar.background': '#eee8d5',
      'sideBar.foreground': '#657b83',
      'sideBar.border': '#ddd6c1',
      'sideBarTitle.foreground': '#586e75',
      'sideBarSectionHeader.background': '#ddd6c1',
      'sideBarSectionHeader.foreground': '#586e75',
      'activityBar.background': '#ddd6c1',
      'activityBar.foreground': '#586e75',
      'activityBar.inactiveForeground': '#93a1a1',
      'activityBarBadge.background': '#268bd2',
      'activityBarBadge.foreground': '#fdf6e3',
      'tab.activeBackground': '#fdf6e3',
      'tab.activeForeground': '#586e75',
      'tab.inactiveBackground': '#eee8d5',
      'tab.inactiveForeground': '#93a1a1',
      'tab.border': '#ddd6c1',
      'tab.activeBorder': '#268bd2',
      'titleBar.activeBackground': '#eee8d5',
      'titleBar.activeForeground': '#586e75',
      'titleBar.inactiveBackground': '#eee8d599',
      'titleBar.inactiveForeground': '#93a1a1',
      'statusBar.background': '#eee8d5',
      'statusBar.foreground': '#586e75',
      'statusBar.border': '#ddd6c1',
      'statusBar.debuggingBackground': '#cb4b16',
      'statusBar.noFolderBackground': '#6c71c4',
      'panel.background': '#fdf6e3',
      'panel.border': '#ddd6c1',
      'panelTitle.activeBorder': '#268bd2',
      'panelTitle.activeForeground': '#586e75',
      'panelTitle.inactiveForeground': '#93a1a1',
      'input.background': '#fdf6e3',
      'input.foreground': '#657b83',
      'input.border': '#ddd6c1',
      'input.placeholderForeground': '#93a1a1',
      'inputOption.activeBorder': '#268bd2',
      'dropdown.background': '#fdf6e3',
      'dropdown.foreground': '#657b83',
      'dropdown.border': '#ddd6c1',
      'button.background': '#268bd2',
      'button.foreground': '#fdf6e3',
      'button.hoverBackground': '#2aa198',
      'list.activeSelectionBackground': '#eee8d5',
      'list.activeSelectionForeground': '#586e75',
      'list.hoverBackground': '#eee8d5cc',
      'list.hoverForeground': '#657b83',
      'list.inactiveSelectionBackground': '#eee8d5',
      'list.highlightForeground': '#268bd2',
      'scrollbar.shadow': '#ddd6c150',
      'scrollbarSlider.background': '#93a1a140',
      'scrollbarSlider.hoverBackground': '#93a1a180',
      'scrollbarSlider.activeBackground': '#93a1a1b3',
      'minimap.background': '#fdf6e3',
      'minimap.selectionHighlight': '#eee8d5',
      'breadcrumb.foreground': '#93a1a1',
      'breadcrumb.focusForeground': '#586e75',
      'breadcrumb.activeSelectionForeground': '#586e75',
      focusBorder: '#268bd2',
      foreground: '#657b83',
      'widget.shadow': '#93a1a130',
      'selection.background': '#eee8d5',
      errorForeground: '#dc322f',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#93a1a1', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#2aa198' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#d33682' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#cb4b16' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#859900' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#859900' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#268bd2' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#b58900' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#657b83' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#657b83' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#268bd2' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#268bd2' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#93a1a1' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#dc322f' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#cb4b16' } },
    ],
  },
]
