import type { ThemeColors, TokenColor } from '@/types'
import { DEFAULT_DARK_COLORS, DEFAULT_TOKEN_COLORS } from './default-theme'

export interface ThemeTemplate {
  id: string
  name: string
  type: 'dark' | 'light'
  description: string
  colors: ThemeColors
  tokenColors: TokenColor[]
}

const LIGHT_BASE_TOKENS: TokenColor[] = [
  { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#008000', fontStyle: 'italic' } },
  { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#a31515' } },
  { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#098658' } },
  { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#0000ff' } },
  { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#0000ff' } },
  { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#000000' } },
  { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#795e26' } },
  { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#267f99' } },
  { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#001080' } },
  { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#001080' } },
  { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#001080' } },
  { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#800000' } },
  { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#e50000' } },
  { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#811f3f' } },
  { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#ee0000' } },
]

export const THEME_TEMPLATES: ThemeTemplate[] = [
  // ===== Classic Dark =====
  {
    id: 'classic-dark',
    name: 'Classic Dark',
    type: 'dark',
    description: 'シンプルで使いやすい定番ダークテーマ',
    colors: { ...DEFAULT_DARK_COLORS },
    tokenColors: [...DEFAULT_TOKEN_COLORS],
  },

  // ===== Classic Light =====
  {
    id: 'classic-light',
    name: 'Classic Light',
    type: 'light',
    description: 'シンプルで使いやすい定番ライトテーマ',
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'editor.lineHighlightBackground': '#f0f0f0',
      'editor.selectionBackground': '#add6ff',
      'editor.selectionHighlightBackground': '#add6ff80',
      'editor.wordHighlightBackground': '#57575740',
      'editor.findMatchBackground': '#a8ac94',
      'editor.findMatchHighlightBackground': '#ea5c0040',
      'editorGutter.background': '#ffffff',
      'editorLineNumber.foreground': '#237893',
      'editorLineNumber.activeForeground': '#0b216f',
      'sideBar.background': '#f3f3f3',
      'sideBar.foreground': '#616161',
      'sideBar.border': '#e5e5e5',
      'sideBarTitle.foreground': '#6f6f6f',
      'sideBarSectionHeader.background': '#e0e0e0',
      'sideBarSectionHeader.foreground': '#6f6f6f',
      'activityBar.background': '#2c2c2c',
      'activityBar.foreground': '#ffffff',
      'activityBar.inactiveForeground': '#ffffff66',
      'activityBarBadge.background': '#007acc',
      'activityBarBadge.foreground': '#ffffff',
      'tab.activeBackground': '#ffffff',
      'tab.activeForeground': '#333333',
      'tab.inactiveBackground': '#ececec',
      'tab.inactiveForeground': '#33333380',
      'tab.border': '#f3f3f3',
      'tab.activeBorder': '#f3f3f3',
      'titleBar.activeBackground': '#dddddd',
      'titleBar.activeForeground': '#333333',
      'titleBar.inactiveBackground': '#dddddd99',
      'titleBar.inactiveForeground': '#33333399',
      'statusBar.background': '#007acc',
      'statusBar.foreground': '#ffffff',
      'statusBar.border': '#e5e5e5',
      'statusBar.debuggingBackground': '#cc6633',
      'statusBar.noFolderBackground': '#68217a',
      'panel.background': '#ffffff',
      'panel.border': '#e5e5e5',
      'panelTitle.activeBorder': '#424242',
      'panelTitle.activeForeground': '#424242',
      'panelTitle.inactiveForeground': '#42424280',
      'input.background': '#ffffff',
      'input.foreground': '#616161',
      'input.border': '#cecece',
      'input.placeholderForeground': '#767676',
      'inputOption.activeBorder': '#007acc',
      'dropdown.background': '#ffffff',
      'dropdown.foreground': '#616161',
      'dropdown.border': '#cecece',
      'button.background': '#007acc',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#0062a3',
      'list.activeSelectionBackground': '#0060c0',
      'list.activeSelectionForeground': '#ffffff',
      'list.hoverBackground': '#e8e8e8',
      'list.hoverForeground': '#2e2e2e',
      'list.inactiveSelectionBackground': '#e4e6f1',
      'list.highlightForeground': '#0066bf',
      'scrollbar.shadow': '#dddddd',
      'scrollbarSlider.background': '#64646466',
      'scrollbarSlider.hoverBackground': '#646464b3',
      'scrollbarSlider.activeBackground': '#00000099',
      'minimap.background': '#ffffff',
      'minimap.selectionHighlight': '#add6ff',
      'breadcrumb.foreground': '#616161',
      'breadcrumb.focusForeground': '#2e2e2e',
      'breadcrumb.activeSelectionForeground': '#2e2e2e',
      focusBorder: '#0090f1',
      foreground: '#616161',
      'widget.shadow': '#a8a8a829',
      'selection.background': '#add6ff',
      errorForeground: '#a1260d',
    },
    tokenColors: LIGHT_BASE_TOKENS,
  },

  // ===== Vivid Jungle =====
  {
    id: 'vivid-jungle',
    name: 'Vivid Jungle',
    type: 'dark',
    description: '鮮やかなグリーンとピンクが映えるダークテーマ',
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#f8f8f2',
      'editor.lineHighlightBackground': '#3e3d32',
      'editor.selectionBackground': '#49483e',
      'editor.selectionHighlightBackground': '#49483e80',
      'editor.wordHighlightBackground': '#49483e',
      'editor.findMatchBackground': '#ffe79260',
      'editor.findMatchHighlightBackground': '#ffe79240',
      'editorGutter.background': '#272822',
      'editorLineNumber.foreground': '#90908a',
      'editorLineNumber.activeForeground': '#c2c2bf',
      'sideBar.background': '#21222c',
      'sideBar.foreground': '#f8f8f2',
      'sideBar.border': '#191a21',
      'sideBarTitle.foreground': '#f8f8f2',
      'sideBarSectionHeader.background': '#21222c',
      'sideBarSectionHeader.foreground': '#f8f8f2',
      'activityBar.background': '#272822',
      'activityBar.foreground': '#f8f8f2',
      'activityBar.inactiveForeground': '#f8f8f266',
      'activityBarBadge.background': '#a6e22e',
      'activityBarBadge.foreground': '#272822',
      'tab.activeBackground': '#272822',
      'tab.activeForeground': '#f8f8f2',
      'tab.inactiveBackground': '#21222c',
      'tab.inactiveForeground': '#f8f8f280',
      'tab.border': '#191a21',
      'tab.activeBorder': '#a6e22e',
      'titleBar.activeBackground': '#1e1f29',
      'titleBar.activeForeground': '#f8f8f2',
      'titleBar.inactiveBackground': '#1e1f2999',
      'titleBar.inactiveForeground': '#f8f8f299',
      'statusBar.background': '#a6e22e',
      'statusBar.foreground': '#272822',
      'statusBar.border': '#191a21',
      'statusBar.debuggingBackground': '#fd971f',
      'statusBar.noFolderBackground': '#ae81ff',
      'panel.background': '#272822',
      'panel.border': '#49483e',
      'panelTitle.activeBorder': '#f8f8f2',
      'panelTitle.activeForeground': '#f8f8f2',
      'panelTitle.inactiveForeground': '#f8f8f280',
      'input.background': '#3e3d32',
      'input.foreground': '#f8f8f2',
      'input.border': '#49483e',
      'input.placeholderForeground': '#f8f8f280',
      'inputOption.activeBorder': '#a6e22e',
      'dropdown.background': '#3e3d32',
      'dropdown.foreground': '#f8f8f2',
      'dropdown.border': '#49483e',
      'button.background': '#a6e22e',
      'button.foreground': '#272822',
      'button.hoverBackground': '#b6f23e',
      'list.activeSelectionBackground': '#49483e',
      'list.activeSelectionForeground': '#f8f8f2',
      'list.hoverBackground': '#3e3d32',
      'list.hoverForeground': '#f8f8f2',
      'list.inactiveSelectionBackground': '#3e3d32',
      'list.highlightForeground': '#a6e22e',
      'scrollbar.shadow': '#00000050',
      'scrollbarSlider.background': '#49483e80',
      'scrollbarSlider.hoverBackground': '#49483eb3',
      'scrollbarSlider.activeBackground': '#49483eff',
      'minimap.background': '#272822',
      'minimap.selectionHighlight': '#49483e',
      'breadcrumb.foreground': '#f8f8f2cc',
      'breadcrumb.focusForeground': '#f8f8f2',
      'breadcrumb.activeSelectionForeground': '#f8f8f2',
      focusBorder: '#a6e22e',
      foreground: '#f8f8f2',
      'widget.shadow': '#00000050',
      'selection.background': '#49483e',
      errorForeground: '#f92672',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#75715e', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#e6db74' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#ae81ff' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#ae81ff' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#f92672' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#f92672' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#a6e22e' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#a6e22e', fontStyle: 'underline' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#f8f8f2' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#fd971f', fontStyle: 'italic' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#f8f8f2' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#f92672' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#a6e22e' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#e6db74' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#ae81ff' } },
    ],
  },

  // ===== Twilight Purple =====
  {
    id: 'twilight-purple',
    name: 'Twilight Purple',
    type: 'dark',
    description: '紫を基調としたモダンなダークテーマ',
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editor.lineHighlightBackground': '#44475a75',
      'editor.selectionBackground': '#44475a',
      'editor.selectionHighlightBackground': '#44475a75',
      'editor.wordHighlightBackground': '#8be9fd50',
      'editor.findMatchBackground': '#ffb86c80',
      'editor.findMatchHighlightBackground': '#ffb86c40',
      'editorGutter.background': '#282a36',
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#f8f8f2',
      'sideBar.background': '#21222c',
      'sideBar.foreground': '#f8f8f2',
      'sideBar.border': '#191a21',
      'sideBarTitle.foreground': '#f8f8f2',
      'sideBarSectionHeader.background': '#21222c',
      'sideBarSectionHeader.foreground': '#f8f8f2',
      'activityBar.background': '#343746',
      'activityBar.foreground': '#f8f8f2',
      'activityBar.inactiveForeground': '#6272a4',
      'activityBarBadge.background': '#ff79c6',
      'activityBarBadge.foreground': '#f8f8f2',
      'tab.activeBackground': '#282a36',
      'tab.activeForeground': '#f8f8f2',
      'tab.inactiveBackground': '#21222c',
      'tab.inactiveForeground': '#6272a4',
      'tab.border': '#191a21',
      'tab.activeBorder': '#ff79c6',
      'titleBar.activeBackground': '#21222c',
      'titleBar.activeForeground': '#f8f8f2',
      'titleBar.inactiveBackground': '#21222c99',
      'titleBar.inactiveForeground': '#6272a4',
      'statusBar.background': '#191a21',
      'statusBar.foreground': '#f8f8f2',
      'statusBar.border': '#191a21',
      'statusBar.debuggingBackground': '#ff5555',
      'statusBar.noFolderBackground': '#191a21',
      'panel.background': '#282a36',
      'panel.border': '#bd93f9',
      'panelTitle.activeBorder': '#ff79c6',
      'panelTitle.activeForeground': '#f8f8f2',
      'panelTitle.inactiveForeground': '#6272a4',
      'input.background': '#282a36',
      'input.foreground': '#f8f8f2',
      'input.border': '#191a21',
      'input.placeholderForeground': '#6272a4',
      'inputOption.activeBorder': '#bd93f9',
      'dropdown.background': '#343746',
      'dropdown.foreground': '#f8f8f2',
      'dropdown.border': '#191a21',
      'button.background': '#44475a',
      'button.foreground': '#f8f8f2',
      'button.hoverBackground': '#6272a4',
      'list.activeSelectionBackground': '#44475a',
      'list.activeSelectionForeground': '#f8f8f2',
      'list.hoverBackground': '#44475a75',
      'list.hoverForeground': '#f8f8f2',
      'list.inactiveSelectionBackground': '#44475a75',
      'list.highlightForeground': '#8be9fd',
      'scrollbar.shadow': '#191a21',
      'scrollbarSlider.background': '#44475a80',
      'scrollbarSlider.hoverBackground': '#44475ab3',
      'scrollbarSlider.activeBackground': '#6272a4',
      'minimap.background': '#282a36',
      'minimap.selectionHighlight': '#44475a',
      'breadcrumb.foreground': '#6272a4',
      'breadcrumb.focusForeground': '#f8f8f2',
      'breadcrumb.activeSelectionForeground': '#f8f8f2',
      focusBorder: '#6272a4',
      foreground: '#f8f8f2',
      'widget.shadow': '#191a2180',
      'selection.background': '#44475a',
      errorForeground: '#ff5555',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#6272a4', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#f1fa8c' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#bd93f9' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#bd93f9' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#ff79c6' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#ff79c6' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#50fa7b' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#8be9fd', fontStyle: 'italic' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#f8f8f2' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#ffb86c', fontStyle: 'italic' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#66d9ef' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#ff79c6' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#50fa7b' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#ff5555' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#ff79c6' } },
    ],
  },

  // ===== Frost Blue =====
  {
    id: 'frost-blue',
    name: 'Frost Blue',
    type: 'dark',
    description: '落ち着いた寒色系の静かなダークテーマ',
    colors: {
      'editor.background': '#2e3440',
      'editor.foreground': '#d8dee9',
      'editor.lineHighlightBackground': '#3b4252',
      'editor.selectionBackground': '#434c5e',
      'editor.selectionHighlightBackground': '#434c5e80',
      'editor.wordHighlightBackground': '#434c5e',
      'editor.findMatchBackground': '#88c0d066',
      'editor.findMatchHighlightBackground': '#88c0d033',
      'editorGutter.background': '#2e3440',
      'editorLineNumber.foreground': '#4c566a',
      'editorLineNumber.activeForeground': '#d8dee9',
      'sideBar.background': '#2e3440',
      'sideBar.foreground': '#d8dee9',
      'sideBar.border': '#3b4252',
      'sideBarTitle.foreground': '#d8dee9',
      'sideBarSectionHeader.background': '#3b4252',
      'sideBarSectionHeader.foreground': '#d8dee9',
      'activityBar.background': '#2e3440',
      'activityBar.foreground': '#d8dee9',
      'activityBar.inactiveForeground': '#4c566a',
      'activityBarBadge.background': '#88c0d0',
      'activityBarBadge.foreground': '#2e3440',
      'tab.activeBackground': '#3b4252',
      'tab.activeForeground': '#d8dee9',
      'tab.inactiveBackground': '#2e3440',
      'tab.inactiveForeground': '#4c566a',
      'tab.border': '#3b4252',
      'tab.activeBorder': '#88c0d0',
      'titleBar.activeBackground': '#2e3440',
      'titleBar.activeForeground': '#d8dee9',
      'titleBar.inactiveBackground': '#2e344099',
      'titleBar.inactiveForeground': '#d8dee999',
      'statusBar.background': '#5e81ac',
      'statusBar.foreground': '#d8dee9',
      'statusBar.border': '#3b4252',
      'statusBar.debuggingBackground': '#d08770',
      'statusBar.noFolderBackground': '#b48ead',
      'panel.background': '#2e3440',
      'panel.border': '#3b4252',
      'panelTitle.activeBorder': '#88c0d0',
      'panelTitle.activeForeground': '#d8dee9',
      'panelTitle.inactiveForeground': '#4c566a',
      'input.background': '#3b4252',
      'input.foreground': '#d8dee9',
      'input.border': '#4c566a',
      'input.placeholderForeground': '#4c566a',
      'inputOption.activeBorder': '#88c0d0',
      'dropdown.background': '#3b4252',
      'dropdown.foreground': '#d8dee9',
      'dropdown.border': '#4c566a',
      'button.background': '#5e81ac',
      'button.foreground': '#d8dee9',
      'button.hoverBackground': '#81a1c1',
      'list.activeSelectionBackground': '#434c5e',
      'list.activeSelectionForeground': '#d8dee9',
      'list.hoverBackground': '#3b4252',
      'list.hoverForeground': '#d8dee9',
      'list.inactiveSelectionBackground': '#3b4252',
      'list.highlightForeground': '#88c0d0',
      'scrollbar.shadow': '#2e344050',
      'scrollbarSlider.background': '#4c566a80',
      'scrollbarSlider.hoverBackground': '#4c566ab3',
      'scrollbarSlider.activeBackground': '#4c566aff',
      'minimap.background': '#2e3440',
      'minimap.selectionHighlight': '#434c5e',
      'breadcrumb.foreground': '#d8dee9cc',
      'breadcrumb.focusForeground': '#d8dee9',
      'breadcrumb.activeSelectionForeground': '#d8dee9',
      focusBorder: '#88c0d0',
      foreground: '#d8dee9',
      'widget.shadow': '#2e344060',
      'selection.background': '#434c5e',
      errorForeground: '#bf616a',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#616e88', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#a3be8c' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#b48ead' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#81a1c1' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#81a1c1' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#81a1c1' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#88c0d0' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#8fbcbb' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#d8dee9' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#d8dee9' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#88c0d0' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#81a1c1' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#8fbcbb' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#ebcb8b' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#ebcb8b' } },
    ],
  },

  // ===== Warm Teal Dark =====
  {
    id: 'warm-teal-dark',
    name: 'Warm Teal Dark',
    type: 'dark',
    description: 'ティールと暖色が調和した目に優しいダークテーマ',
    colors: {
      'editor.background': '#002b36',
      'editor.foreground': '#839496',
      'editor.lineHighlightBackground': '#073642',
      'editor.selectionBackground': '#274642',
      'editor.selectionHighlightBackground': '#27464280',
      'editor.wordHighlightBackground': '#073642',
      'editor.findMatchBackground': '#b5890060',
      'editor.findMatchHighlightBackground': '#b5890030',
      'editorGutter.background': '#002b36',
      'editorLineNumber.foreground': '#586e75',
      'editorLineNumber.activeForeground': '#93a1a1',
      'sideBar.background': '#00252e',
      'sideBar.foreground': '#839496',
      'sideBar.border': '#073642',
      'sideBarTitle.foreground': '#93a1a1',
      'sideBarSectionHeader.background': '#073642',
      'sideBarSectionHeader.foreground': '#93a1a1',
      'activityBar.background': '#002b36',
      'activityBar.foreground': '#839496',
      'activityBar.inactiveForeground': '#586e75',
      'activityBarBadge.background': '#268bd2',
      'activityBarBadge.foreground': '#fdf6e3',
      'tab.activeBackground': '#002b36',
      'tab.activeForeground': '#fdf6e3',
      'tab.inactiveBackground': '#00252e',
      'tab.inactiveForeground': '#586e75',
      'tab.border': '#073642',
      'tab.activeBorder': '#268bd2',
      'titleBar.activeBackground': '#00252e',
      'titleBar.activeForeground': '#839496',
      'titleBar.inactiveBackground': '#00252e99',
      'titleBar.inactiveForeground': '#83949699',
      'statusBar.background': '#073642',
      'statusBar.foreground': '#839496',
      'statusBar.border': '#073642',
      'statusBar.debuggingBackground': '#cb4b16',
      'statusBar.noFolderBackground': '#6c71c4',
      'panel.background': '#002b36',
      'panel.border': '#073642',
      'panelTitle.activeBorder': '#268bd2',
      'panelTitle.activeForeground': '#93a1a1',
      'panelTitle.inactiveForeground': '#586e75',
      'input.background': '#073642',
      'input.foreground': '#839496',
      'input.border': '#586e75',
      'input.placeholderForeground': '#586e75',
      'inputOption.activeBorder': '#268bd2',
      'dropdown.background': '#073642',
      'dropdown.foreground': '#839496',
      'dropdown.border': '#586e75',
      'button.background': '#268bd2',
      'button.foreground': '#fdf6e3',
      'button.hoverBackground': '#2aa198',
      'list.activeSelectionBackground': '#073642',
      'list.activeSelectionForeground': '#fdf6e3',
      'list.hoverBackground': '#073642cc',
      'list.hoverForeground': '#839496',
      'list.inactiveSelectionBackground': '#073642',
      'list.highlightForeground': '#268bd2',
      'scrollbar.shadow': '#002b3650',
      'scrollbarSlider.background': '#586e7580',
      'scrollbarSlider.hoverBackground': '#586e75b3',
      'scrollbarSlider.activeBackground': '#586e75ff',
      'minimap.background': '#002b36',
      'minimap.selectionHighlight': '#274642',
      'breadcrumb.foreground': '#839496',
      'breadcrumb.focusForeground': '#93a1a1',
      'breadcrumb.activeSelectionForeground': '#fdf6e3',
      focusBorder: '#268bd2',
      foreground: '#839496',
      'widget.shadow': '#002b3680',
      'selection.background': '#274642',
      errorForeground: '#dc322f',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#586e75', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#2aa198' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#d33682' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#cb4b16' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#859900' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#859900' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#268bd2' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#b58900' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#839496' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#839496' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#268bd2' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#268bd2' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#93a1a1' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#dc322f' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#cb4b16' } },
    ],
  },

  // ===== Midnight Ink =====
  {
    id: 'midnight-ink',
    name: 'Midnight Ink',
    type: 'dark',
    description: '深い漆黒にクリアな色彩が映えるモダンテーマ',
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#c9d1d9',
      'editor.lineHighlightBackground': '#161b22',
      'editor.selectionBackground': '#264f78',
      'editor.selectionHighlightBackground': '#264f7840',
      'editor.wordHighlightBackground': '#264f78',
      'editor.findMatchBackground': '#9e6a03aa',
      'editor.findMatchHighlightBackground': '#f2cc6050',
      'editorGutter.background': '#0d1117',
      'editorLineNumber.foreground': '#484f58',
      'editorLineNumber.activeForeground': '#c9d1d9',
      'sideBar.background': '#010409',
      'sideBar.foreground': '#c9d1d9',
      'sideBar.border': '#21262d',
      'sideBarTitle.foreground': '#c9d1d9',
      'sideBarSectionHeader.background': '#010409',
      'sideBarSectionHeader.foreground': '#c9d1d9',
      'activityBar.background': '#0d1117',
      'activityBar.foreground': '#c9d1d9',
      'activityBar.inactiveForeground': '#484f58',
      'activityBarBadge.background': '#1f6feb',
      'activityBarBadge.foreground': '#ffffff',
      'tab.activeBackground': '#0d1117',
      'tab.activeForeground': '#c9d1d9',
      'tab.inactiveBackground': '#010409',
      'tab.inactiveForeground': '#8b949e',
      'tab.border': '#21262d',
      'tab.activeBorder': '#f78166',
      'titleBar.activeBackground': '#010409',
      'titleBar.activeForeground': '#c9d1d9',
      'titleBar.inactiveBackground': '#01040999',
      'titleBar.inactiveForeground': '#8b949e',
      'statusBar.background': '#0d1117',
      'statusBar.foreground': '#8b949e',
      'statusBar.border': '#21262d',
      'statusBar.debuggingBackground': '#da3633',
      'statusBar.noFolderBackground': '#0d1117',
      'panel.background': '#0d1117',
      'panel.border': '#21262d',
      'panelTitle.activeBorder': '#f78166',
      'panelTitle.activeForeground': '#c9d1d9',
      'panelTitle.inactiveForeground': '#8b949e',
      'input.background': '#0d1117',
      'input.foreground': '#c9d1d9',
      'input.border': '#21262d',
      'input.placeholderForeground': '#484f58',
      'inputOption.activeBorder': '#1f6feb',
      'dropdown.background': '#161b22',
      'dropdown.foreground': '#c9d1d9',
      'dropdown.border': '#21262d',
      'button.background': '#238636',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#2ea043',
      'list.activeSelectionBackground': '#163d6180',
      'list.activeSelectionForeground': '#c9d1d9',
      'list.hoverBackground': '#161b22',
      'list.hoverForeground': '#c9d1d9',
      'list.inactiveSelectionBackground': '#161b22',
      'list.highlightForeground': '#58a6ff',
      'scrollbar.shadow': '#01040980',
      'scrollbarSlider.background': '#484f5880',
      'scrollbarSlider.hoverBackground': '#484f58b3',
      'scrollbarSlider.activeBackground': '#484f58ff',
      'minimap.background': '#0d1117',
      'minimap.selectionHighlight': '#264f78',
      'breadcrumb.foreground': '#8b949e',
      'breadcrumb.focusForeground': '#c9d1d9',
      'breadcrumb.activeSelectionForeground': '#c9d1d9',
      focusBorder: '#1f6feb',
      foreground: '#c9d1d9',
      'widget.shadow': '#01040980',
      'selection.background': '#264f78',
      errorForeground: '#f85149',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#8b949e', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#a5d6ff' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#79c0ff' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#79c0ff' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#ff7b72' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#ff7b72' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#d2a8ff' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#ffa657' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#ffa657' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#c9d1d9' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#79c0ff' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#7ee787' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#79c0ff' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#a5d6ff' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#79c0ff' } },
    ],
  },

  // ===== Dusk Harmony =====
  {
    id: 'dusk-harmony',
    name: 'Dusk Harmony',
    type: 'dark',
    description: '調和のとれた配色で長時間でも疲れにくいダークテーマ',
    colors: {
      'editor.background': '#282c34',
      'editor.foreground': '#abb2bf',
      'editor.lineHighlightBackground': '#2c313c',
      'editor.selectionBackground': '#3e4451',
      'editor.selectionHighlightBackground': '#3e445180',
      'editor.wordHighlightBackground': '#3e4451',
      'editor.findMatchBackground': '#d19a6680',
      'editor.findMatchHighlightBackground': '#d19a6640',
      'editorGutter.background': '#282c34',
      'editorLineNumber.foreground': '#495162',
      'editorLineNumber.activeForeground': '#abb2bf',
      'sideBar.background': '#21252b',
      'sideBar.foreground': '#abb2bf',
      'sideBar.border': '#181a1f',
      'sideBarTitle.foreground': '#abb2bf',
      'sideBarSectionHeader.background': '#21252b',
      'sideBarSectionHeader.foreground': '#abb2bf',
      'activityBar.background': '#282c34',
      'activityBar.foreground': '#abb2bf',
      'activityBar.inactiveForeground': '#495162',
      'activityBarBadge.background': '#528bff',
      'activityBarBadge.foreground': '#ffffff',
      'tab.activeBackground': '#282c34',
      'tab.activeForeground': '#dcdfe4',
      'tab.inactiveBackground': '#21252b',
      'tab.inactiveForeground': '#5c6370',
      'tab.border': '#181a1f',
      'tab.activeBorder': '#528bff',
      'titleBar.activeBackground': '#282c34',
      'titleBar.activeForeground': '#9da5b4',
      'titleBar.inactiveBackground': '#282c3499',
      'titleBar.inactiveForeground': '#9da5b499',
      'statusBar.background': '#21252b',
      'statusBar.foreground': '#9da5b4',
      'statusBar.border': '#181a1f',
      'statusBar.debuggingBackground': '#be5046',
      'statusBar.noFolderBackground': '#21252b',
      'panel.background': '#282c34',
      'panel.border': '#3e4451',
      'panelTitle.activeBorder': '#528bff',
      'panelTitle.activeForeground': '#abb2bf',
      'panelTitle.inactiveForeground': '#5c6370',
      'input.background': '#1d2025',
      'input.foreground': '#abb2bf',
      'input.border': '#3e4451',
      'input.placeholderForeground': '#5c6370',
      'inputOption.activeBorder': '#528bff',
      'dropdown.background': '#1d2025',
      'dropdown.foreground': '#abb2bf',
      'dropdown.border': '#3e4451',
      'button.background': '#4d78cc',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#6187d2',
      'list.activeSelectionBackground': '#2c313a',
      'list.activeSelectionForeground': '#d7dae0',
      'list.hoverBackground': '#2c313a',
      'list.hoverForeground': '#abb2bf',
      'list.inactiveSelectionBackground': '#2c313a',
      'list.highlightForeground': '#528bff',
      'scrollbar.shadow': '#21252b80',
      'scrollbarSlider.background': '#4e566680',
      'scrollbarSlider.hoverBackground': '#5a637580',
      'scrollbarSlider.activeBackground': '#747d9180',
      'minimap.background': '#282c34',
      'minimap.selectionHighlight': '#3e4451',
      'breadcrumb.foreground': '#5c6370',
      'breadcrumb.focusForeground': '#abb2bf',
      'breadcrumb.activeSelectionForeground': '#abb2bf',
      focusBorder: '#528bff',
      foreground: '#abb2bf',
      'widget.shadow': '#21252b80',
      'selection.background': '#3e4451',
      errorForeground: '#e06c75',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#5c6370', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#98c379' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#d19a66' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#d19a66' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#c678dd' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#56b6c2' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#61afef' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#e5c07b' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#e06c75' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#abb2bf' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#e06c75' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#e06c75' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#d19a66' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#56b6c2' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#56b6c2' } },
    ],
  },

  // ===== Warm Teal Light =====
  {
    id: 'warm-teal-light',
    name: 'Warm Teal Light',
    type: 'light',
    description: 'ティールと暖色が調和した目に優しいライトテーマ',
    colors: {
      'editor.background': '#fdf6e3',
      'editor.foreground': '#657b83',
      'editor.lineHighlightBackground': '#eee8d5',
      'editor.selectionBackground': '#eee8d5',
      'editor.selectionHighlightBackground': '#eee8d580',
      'editor.wordHighlightBackground': '#eee8d5',
      'editor.findMatchBackground': '#b5890060',
      'editor.findMatchHighlightBackground': '#b5890030',
      'editorGutter.background': '#fdf6e3',
      'editorLineNumber.foreground': '#93a1a1',
      'editorLineNumber.activeForeground': '#586e75',
      'sideBar.background': '#eee8d5',
      'sideBar.foreground': '#657b83',
      'sideBar.border': '#ddd6c1',
      'sideBarTitle.foreground': '#586e75',
      'sideBarSectionHeader.background': '#ddd6c1',
      'sideBarSectionHeader.foreground': '#586e75',
      'activityBar.background': '#ddd6c1',
      'activityBar.foreground': '#586e75',
      'activityBar.inactiveForeground': '#93a1a1',
      'activityBarBadge.background': '#268bd2',
      'activityBarBadge.foreground': '#fdf6e3',
      'tab.activeBackground': '#fdf6e3',
      'tab.activeForeground': '#586e75',
      'tab.inactiveBackground': '#eee8d5',
      'tab.inactiveForeground': '#93a1a1',
      'tab.border': '#ddd6c1',
      'tab.activeBorder': '#268bd2',
      'titleBar.activeBackground': '#eee8d5',
      'titleBar.activeForeground': '#586e75',
      'titleBar.inactiveBackground': '#eee8d599',
      'titleBar.inactiveForeground': '#93a1a1',
      'statusBar.background': '#eee8d5',
      'statusBar.foreground': '#586e75',
      'statusBar.border': '#ddd6c1',
      'statusBar.debuggingBackground': '#cb4b16',
      'statusBar.noFolderBackground': '#6c71c4',
      'panel.background': '#fdf6e3',
      'panel.border': '#ddd6c1',
      'panelTitle.activeBorder': '#268bd2',
      'panelTitle.activeForeground': '#586e75',
      'panelTitle.inactiveForeground': '#93a1a1',
      'input.background': '#fdf6e3',
      'input.foreground': '#657b83',
      'input.border': '#ddd6c1',
      'input.placeholderForeground': '#93a1a1',
      'inputOption.activeBorder': '#268bd2',
      'dropdown.background': '#fdf6e3',
      'dropdown.foreground': '#657b83',
      'dropdown.border': '#ddd6c1',
      'button.background': '#268bd2',
      'button.foreground': '#fdf6e3',
      'button.hoverBackground': '#2aa198',
      'list.activeSelectionBackground': '#eee8d5',
      'list.activeSelectionForeground': '#586e75',
      'list.hoverBackground': '#eee8d5cc',
      'list.hoverForeground': '#657b83',
      'list.inactiveSelectionBackground': '#eee8d5',
      'list.highlightForeground': '#268bd2',
      'scrollbar.shadow': '#ddd6c150',
      'scrollbarSlider.background': '#93a1a140',
      'scrollbarSlider.hoverBackground': '#93a1a180',
      'scrollbarSlider.activeBackground': '#93a1a1b3',
      'minimap.background': '#fdf6e3',
      'minimap.selectionHighlight': '#eee8d5',
      'breadcrumb.foreground': '#93a1a1',
      'breadcrumb.focusForeground': '#586e75',
      'breadcrumb.activeSelectionForeground': '#586e75',
      focusBorder: '#268bd2',
      foreground: '#657b83',
      'widget.shadow': '#93a1a130',
      'selection.background': '#eee8d5',
      errorForeground: '#dc322f',
    },
    tokenColors: [
      { name: 'Comment', scope: ['comment', 'comment.line', 'comment.block'], settings: { foreground: '#93a1a1', fontStyle: 'italic' } },
      { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#2aa198' } },
      { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#d33682' } },
      { name: 'Constant', scope: ['constant', 'constant.language'], settings: { foreground: '#cb4b16' } },
      { name: 'Keyword', scope: ['keyword', 'keyword.control'], settings: { foreground: '#859900' } },
      { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#859900' } },
      { name: 'Function', scope: ['entity.name.function'], settings: { foreground: '#268bd2' } },
      { name: 'Class', scope: ['entity.name.class', 'entity.name.type'], settings: { foreground: '#b58900' } },
      { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#657b83' } },
      { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#657b83' } },
      { name: 'Property', scope: ['variable.other.property'], settings: { foreground: '#268bd2' } },
      { name: 'Tag', scope: ['entity.name.tag'], settings: { foreground: '#268bd2' } },
      { name: 'Attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#93a1a1' } },
      { name: 'Regexp', scope: ['string.regexp'], settings: { foreground: '#dc322f' } },
      { name: 'Escape', scope: ['constant.character.escape'], settings: { foreground: '#cb4b16' } },
    ],
  },
]
